// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinCtrl;

  WeixinCtrl = require("./../ctrl/weixinCtrl");

  exports.check = function(req, res) {
    var echostr, nonce, signature, timestamp;
    signature = req.query.signature;
    timestamp = req.query.timestamp;
    nonce = req.query.nonce;
    echostr = req.query.echostr;
    return WeixinCtrl.check(signature, timestamp, nonce, echostr, function(err, results) {
      if (global.isDebug) {
        console.log("WeixinAction.check:", signature, timestamp, nonce, echostr, err, results);
      }
      return res.send(results);
    });
  };

  exports.msg = function(req, res) {
    var msg, nonce, signature, timestamp;
    signature = req.body.signature;
    timestamp = req.body.timestamp;
    nonce = req.body.nonce;
    msg = req.body.msg;
    return WeixinCtrl.msg(signature, timestamp, nonce, msg, function(err, results) {
      if (global.isDebug) {
        console.log("WeixinAction.msg:", signature, timestamp, nonce, msg, err, results);
      }
      return res.send(results);
    });
  };

}).call(this);
