// Generated by CoffeeScript 1.8.0
(function() {
  var Q, WeixinCtrl;

  WeixinCtrl = require("./../ctrl/weixinCtrl");

  Q = require("q");

  exports.check = function(req, res) {
    var echostr, nonce, signature, timestamp;
    signature = req.query.signature;
    timestamp = req.query.timestamp;
    nonce = req.query.nonce;
    echostr = req.query.echostr;
    return WeixinCtrl.check(signature, timestamp, nonce, echostr, function(err, results) {
      if (global.isDebug) {
        console.log("WeixinAction.check:", signature, timestamp, nonce, echostr, err, results);
      }
      return res.send(results);
    });
  };

  exports.msg = function(req, res) {
    var bodyReader, nonce, signature, timestamp;
    signature = req.query.signature;
    timestamp = req.query.timestamp;
    nonce = req.query.nonce;
    bodyReader = function(req) {
      var deferred, _data;
      deferred = Q.defer();
      _data = "";
      req.on("data", function(chunk) {
        return _data += chunk;
      });
      req.on("end", function() {
        return deferred.resolve(_data);
      });
      return req.on("error", function(e) {
        return deferred.reject(e);
      });
    };
    return bodyReader(req.then(function(results) {
      var msg;
      msg = results;
      return WeixinCtrl.msg(signature, timestamp, nonce, msg, function(err, results) {
        if (global.isDebug) {
          console.log("WeixinAction.msg:", signature, timestamp, nonce, msg, err, results);
        }
        return res.send(results);
      });
    }));
  };

}).call(this);
