// Generated by CoffeeScript 1.8.0
(function() {
  var Promise, WeixinCtrl;

  WeixinCtrl = require("./../ctrl/weixinCtrl");

  Promise = require("promise");

  exports.check = function(req, res) {
    var echostr, nonce, signature, timestamp;
    signature = req.query.signature;
    timestamp = req.query.timestamp;
    nonce = req.query.nonce;
    echostr = req.query.echostr;
    return WeixinCtrl.check(signature, timestamp, nonce, echostr, function(err, results) {
      if (global.isDebug) {
        console.log("WeixinAction.check:", signature, timestamp, nonce, echostr, err, results);
      }
      return res.send(results);
    });
  };

  exports.msg = function(req, res) {
    var bodyReader, nonce, signature, timestamp;
    signature = req.query.signature;
    timestamp = req.query.timestamp;
    nonce = req.query.nonce;
    bodyReader = new Promise(function(resolve, reject) {
      var _data;
      _data = "";
      req.on("data", function(chunk) {
        return _data += chunk;
      });
      req.on("end", function() {
        return resolve(_data);
      });
      return req.on("error", function(e) {
        return reject(e);
      });
    });
    return bodyReader().then(function(res) {
      var msg;
      msg = res;
      WeixinCtrl.msg(signature, timestamp, nonce, msg, function(err, results) {});
      if (global.isDebug) {
        console.log("WeixinAction.msg:", signature, timestamp, nonce, msg, err, results);
      }
      return res.send(results);
    });
  };

}).call(this);
