// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinAction, express, router;

  express = require("express");

  router = express.Router();

  WeixinAction = require("./../action/weixinAction");

  router.get("/", WeixinAction.check);

  router.post("/", WeixinAction.msg);

  module.exports = router;

}).call(this);
