// Generated by CoffeeScript 1.8.0
(function() {
  var CustomerCtrl, Q, WeixinCtrl, config, request;

  request = require("request");

  config = require("./../config/config.json");

  CustomerCtrl = require("./customerCtrl");

  Q = require("q");

  WeixinCtrl = (function() {
    function WeixinCtrl() {}

    WeixinCtrl.check = function(signature, timestamp, nonce, echostr, fn) {
      var url;
      url = "" + config.weixin.host + ":" + config.weixin.port + "/weixin/" + global.ent + "?signature=" + signature + "&timestamp=" + timestamp + "&nonce=" + nonce + "&echostr=" + echostr;
      return request({
        url: url,
        timeout: 3000,
        method: "GET"
      }, function(err, response, body) {
        if (err) {
          return fn(err);
        } else {
          return fn(null, body);
        }
      });
    };

    WeixinCtrl.msg = function(signature, timestamp, nonce, msg, fn) {
      var url;
      url = "" + config.weixin.host + ":" + config.weixin.port + "/weixin/" + global.ent;
      return request({
        url: url,
        timeout: 3000,
        method: "POST",
        form: {
          signature: signature,
          timestamp: timestamp,
          nonce: nonce,
          msg: msg
        }
      }, function(err, response, body) {
        var error, res;
        if (err) {
          return fn(err);
        } else {
          try {
            res = JSON.parse(body);
            if (res.error === 1) {
              return fn(new Error(res.errMsg));
            } else {
              return fn(null, res);
            }
          } catch (_error) {
            error = _error;
            return fn(new Error("Parse Error"));
          }
        }
      });
    };

    WeixinCtrl.event = function(msgObj, fn) {
      var eventType;
      eventType = msgObj.xml.Event[0];
      switch (eventType) {
        case "subscribe":
          return CustomerCtrl.weixinSubscribe(msgObj.xml.FromUserName[0], function(err, res) {
            return fn(err, res);
          });
        case "SCAN":
          return CustomerCtrl.weixinCoupon(msgObj.xml.FromUserName[0], msgObj.xml.EventKey[0], function(err, res) {
            if (err) {
              return fn(null, "<xml>\n<ToUserName><![CDATA[" + msgObj.xml.FromUserName[0] + "]]></ToUserName>\n<FromUserName><![CDATA[" + msgObj.xml.ToUserName[0] + "]]></FromUserName>\n<CreateTime>" + (Date.now()) + "</CreateTime>\n<MsgType><![CDATA[text]]></MsgType>\n<Content><![CDATA[" + err.message + "]]></Content>\n</xml>");
            } else {
              return fn(null, res);
            }
          });
        default:
          return fn(null, "");
      }
    };

    WeixinCtrl.text = function(msgObj, fn) {
      return fn(null, "");
    };

    return WeixinCtrl;

  })();

  module.exports = WeixinCtrl;

}).call(this);
