// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinCtrl, config, request;

  request = require("request");

  config = require("./../config/config.json");

  WeixinCtrl = (function() {
    function WeixinCtrl() {}

    WeixinCtrl.check = function(signature, timestamp, nonce, echostr, fn) {
      var url;
      url = "" + config.weixin.host + ":" + config.weixin.port + "/weixin/" + global.ent + "?signature=" + signature + "&timestamp=" + timestamp + "&nonce=" + nonce + "&echostr=" + echostr;
      return request({
        url: url,
        timeout: 3000,
        method: "GET"
      }, function(err, response, body) {
        if (err) {
          return fn(err);
        } else {
          return fn(null, body);
        }
      });
    };

    WeixinCtrl.msg = function(signature, timestamp, nonce, msg, fn) {
      var url;
      url = "" + config.weixin.host + ":" + config.weixin.port + "/weixin/" + global.ent;
      return request({
        url: url,
        timeout: 3000,
        method: "POST",
        form: {
          signature: signature,
          timestamp: timestamp,
          nonce: nonce,
          msg: msg
        }
      }, function(err, response, body) {
        var error, res;
        if (err) {
          return fn(err);
        } else {
          try {
            res = JSON.parse(body);
            if ((res.error != null) === 1) {
              return fn(new Error(res.errMsg));
            } else {
              return fn(null, res);
            }
          } catch (_error) {
            error = _error;
            return fn(new Error("Parse Error"));
          }
        }
      });
    };

    WeixinCtrl.subscribe = function(msgObj, fn) {
      return fn(null, "");
    };

    return WeixinCtrl;

  })();

  module.exports = WeixinCtrl;

}).call(this);
