// Generated by CoffeeScript 1.8.0
(function() {
  var dateExtend;

  dateExtend = function() {
    return Date.prototype.Format = function(fmt) {
      var getWeek, key, o, value;
      getWeek = function(w) {
        var x;
        switch (w) {
          case 0:
            return x = "周日";
          case 1:
            return x = "周一";
          case 2:
            return x = "周二";
          case 3:
            return x = "周三";
          case 4:
            return x = "周四";
          case 5:
            return x = "周五";
          case 6:
            return x = "周六";
        }
      };
      o = {
        "M+": this.getMonth() + 1,
        "d+": this.getDate(),
        "h+": this.getHours(),
        "m+": this.getMinutes(),
        "s+": this.getSeconds(),
        "q+": Math.floor((this.getMonth() + 3) / 3),
        "S": this.getMilliseconds(),
        "W": getWeek(this.getDay())
      };
      if (/(y+)/.test(fmt)) {
        fmt = fmt.replace(RegExp.$1, ("" + (this.getFullYear())).substr(4 - RegExp.$1.length));
      }
      for (key in o) {
        value = o[key];
        if (new RegExp("(" + key + ")").test(fmt)) {
          fmt = fmt.replace(RegExp.$1, (RegExp.$1.length === 1 ? value : ("00" + value).substr(("" + value).length)));
        }
      }
      return fmt;
    };
  };

  module.exports = dateExtend;

}).call(this);
